### ISSUE TITLE
[Enhancement suggestion] Target more than one token at a time

### ISSUE THREAD

**Issue by lucaspicerni** [dev7355608/manage-player-targets#1]
Hi! First of all, excellent module! It solved the problem of older friends who are not very familiar with computers asking how to target one more time.

Would it be possible to implement the option, when I have more than one token selected, to change the player's target for all of them together, at the same time? This saved a few clicks in some situations!

Thank you!

**Comment by dev7355608** [comment]
Done: https://github.com/dev7355608/manage-player-targets/releases/tag/v1.1.0
