### ISSUE TITLE
Activate targeting for all logged in players

### ISSUE THREAD

**Issue by Shaula-bellosguardo** [dev7355608/manage-player-targets#3]
My group and I play in person. We do this by using a module (sheet-only) that allows us to view only the character sheet on smartphones while disabling the view of the canvas by the player connected with the mobile device. This prevents the DM from targeting for players since they do not appear in the drop-down menu. Would it please be possible to include an option to enable all logged in players?

**Comment by dev7355608** [comment]
That's not possible, I'm afraid, at least not with the core targeting, because the targets of a user are specific to the scene they are viewing and, if the canvas is disabled, they are not viewing any scene, and therefore cannot have any targets.
